### ISSUE TITLE
mist-bin doesn't exist 

### ISSUE THREAD

**Issue by DioEgizio** [makedeb/makedeb-docs#59]
mist-bin doesn't exist and this might cause some confusion for the users seeing https://docs.makedeb.org/using-the-mpr/mist-the-mpr-cli/#installing-mist

**Comment by hwittenborn** [comment]
The last time I checked it existed: https://mpr.makedeb.org/packages/mist-bin, is that page returning a not found page (or something similar) for you?

**Comment by DioEgizio** [comment]
Huh, before returned a 404. I guess it's fixed now
